2024-07-02T12:18:10 {"cpu": 0.10693359375, "cpu_total": 12, "cpu_usage": 0.0089111328125, "memory": 3460.0, "memory_total": 9955.0, "memory_usage": 0.347564038171773, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "Pipeline data_processing for run 1 in schedule 1 is alive.", "timestamp": 1719922690.071386, "uuid": "90a75cd24a1949838c3f52be773a239d"}
2024-07-02T12:18:10 {"cpu": 0.10693359375, "cpu_total": 12, "cpu_usage": 0.0089111328125, "memory": 3493.0, "memory_total": 9955.0, "memory_usage": 0.3508789552988448, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "Pipeline data_processing for run 1 in schedule 1 is alive.", "timestamp": 1719922690.237822, "uuid": "b032d820b14c4af68bbd9aaf8054ad17"}
2024-07-02T12:18:10 {"block_run_id": 1, "block_uuid": "load_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 1: pipeline data_processing block load_data", "timestamp": 1719922690.265305, "uuid": "b1471ac641394280affb12f6486a1d52"}
2024-07-02T12:18:10 {"block_run_id": 1, "block_uuid": "load_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "BlockRun 1 (block_uuid: load_data) completes.", "timestamp": 1719922690.830343, "uuid": "6e927dacf28842e195c78a7a49eb7319"}
2024-07-02T12:18:19 {"cpu": 0.11083984375, "cpu_total": 12, "cpu_usage": 0.009236653645833334, "memory": 3474.0, "memory_total": 9955.0, "memory_usage": 0.34897036664992465, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "Pipeline data_processing for run 1 in schedule 1 is alive.", "timestamp": 1719922699.419626, "uuid": "7d1b7e8a7d3e41bd89339f83a611f520"}
2024-07-02T12:18:19 {"block_run_id": 2, "block_uuid": "filter_columns", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 2: pipeline data_processing block filter_columns", "timestamp": 1719922699.587637, "uuid": "97185e0078a744dd9aef618ce77fdbdd"}
2024-07-02T12:18:19 {"block_run_id": 2, "block_uuid": "filter_columns", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "BlockRun 2 (block_uuid: filter_columns) completes.", "timestamp": 1719922699.919006, "uuid": "cb3306ece1d24d899b3d4b32123cce03"}
2024-07-02T12:18:29 {"cpu": 0.10888671875, "cpu_total": 12, "cpu_usage": 0.009073893229166666, "memory": 3478.0, "memory_total": 9955.0, "memory_usage": 0.3493721747865394, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "Pipeline data_processing for run 1 in schedule 1 is alive.", "timestamp": 1719922709.660492, "uuid": "6e0c3532f4c443018d5b45be3eafe3dd"}
2024-07-02T12:18:29 {"block_run_id": 3, "block_uuid": "split_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 3: pipeline data_processing block split_data", "timestamp": 1719922709.826017, "uuid": "6204714b12ad4c5c88c2d9005123d182"}
2024-07-02T12:18:30 {"block_run_id": 3, "block_uuid": "split_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "BlockRun 3 (block_uuid: split_data) completes.", "timestamp": 1719922710.759071, "uuid": "9223225a79c24667a892708b871278c7"}
2024-07-02T12:18:39 {"cpu": 0.10693359375, "cpu_total": 12, "cpu_usage": 0.0089111328125, "memory": 3480.0, "memory_total": 9955.0, "memory_usage": 0.3495730788548468, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "Pipeline data_processing for run 1 in schedule 1 is alive.", "timestamp": 1719922719.898424, "uuid": "1fa93432d1a540afa44a4c9bf9919c91"}
2024-07-02T12:18:40 {"block_run_id": 4, "block_uuid": "transformations", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 4: pipeline data_processing block transformations", "timestamp": 1719922720.062708, "uuid": "be56b94fb9534f48ab208c3237bb1dd7"}
2024-07-02T12:18:40 {"block_run_id": 4, "block_uuid": "transformations", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "EXCEPTION", "message": "BlockRun 4 (block_uuid: transformations) failed.", "timestamp": 1719922720.178837, "uuid": "13430ac4174d4c33b2325295367bb87d", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 605, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 578, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1052, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1285, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1194, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1509, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1637, in _execute_block\n    exec(self.content, results)\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'mlflow'\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1580, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 581, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 107, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 173, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 275, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 240, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1105, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["No module named 'mlflow'"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 605, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 578, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1052, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1285, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1194, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1509, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1637, in _execute_block
    exec(self.content, results)
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'mlflow'
2024-07-02T12:18:49 {"cpu": 0.10498046875, "cpu_total": 12, "cpu_usage": 0.008748372395833334, "memory": 3499.0, "memory_total": 9955.0, "memory_usage": 0.35148166750376697, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "data_processing", "hostname": "bac4e290ad80", "level": "INFO", "message": "Pipeline data_processing for run 1 in schedule 1 is alive.", "timestamp": 1719922729.13512, "uuid": "d2a878b64f864164ab82ddb22d80e697"}
